version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 99
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: react-navigation
    versions:
    - 4.4.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: jest-expo
    versions:
    - 34.0.1
  - dependency-name: expo
    versions:
    - 40.0.1
    - 41.0.0
  - dependency-name: "@types/react-native"
    versions:
    - 0.63.46
    - 0.63.47
    - 0.63.48
    - 0.63.49
    - 0.63.50
    - 0.63.51
    - 0.63.52
    - 0.64.0
    - 0.64.1
    - 0.64.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@expo/vector-icons"
    versions:
    - 12.0.3
