language: node_js
node_js:
  - 'node'
cache:
  yarn: true
  directories:
    - node_modules
addons:
  sonarcloud:
    organization: 'ankitprahladsoni-github'
    token:
      secure: $SONAR_TOKEN
env:
  - TEST_SUITE="yarn jest --coverage"
  - TEST_SUITE="yarn tslint -t json -o report.json --force"
  - TEST_SUITE="sonar-scanner"
script: $TEST_SUITE
notifications:
  email: false
after_success:
  - yarn global add codecov
  - codecov
