language: node_js
node_js:
  - 'node'
cache:
  yarn: true
  directories:
    - node_modules
addons:
  sonarcloud:
    organization: 'ankitprahladsoni-github'
    token:
      secure: $SONAR_TOKEN
script:
  - yarn jest --coverage --no-cache
  - yarn tslint -t json -o report.json --force
  - sonar-scanner
notifications:
  email: false
after_success:
  - yarn global add codecov
  - codecov
