language: node_js
node_js:
  - 'node'
cache:
  yarn: true
  directories:
    - node_modules
addons:
  sonarcloud:
    organization: 'ankitprahladsoni-github'
    token:
      secure: $SONAR_TOKEN
script:
  - yarn test --coverage
  - yarn tslint -t json -o report.json --force
  - sonar-scanner
notifications:
  email: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
after_success:
  - yarn global add codecov
  - codecov
